[tool.pyright]
ignore = [
    "**/node_modules",
    "**/__pycache__",
    "**/*.ipynb",
    ".git"
]

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | \.eggs
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''
